services:
  octopus:
    image: ghcr.io/seller-1990/octopus:${OCTOPUS_IMAGE_TAG:-latest}
    ports:
       - '8080:8080'
    volumes:      
       - '/path/to/data:/app/data'
    container_name: octopus
    restart: unless-stopped
