FROM alpine

ARG TARGETPLATFORM
ENV TZ=Asia/Shanghai

RUN apk add --no-cache alpine-conf ca-certificates su-exec && \
    /usr/sbin/setup-timezone -z Asia/Shanghai && \
    apk del alpine-conf && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /app /app/data

COPY build/docker/${TARGETPLATFORM}/octopus /app/octopus
COPY scripts/dockerfiles/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh /app/octopus

VOLUME /app/data
ENTRYPOINT ["/entrypoint.sh"]
CMD ["start"]
